version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ultraseek-postgres
    restart: always
    environment:
      POSTGRES_USER: ultraseek
      POSTGRES_PASSWORD: ultraseek
      POSTGRES_DB: ultraseek
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
