"""add thread_id

Revision ID: 85139750dc79
Revises: 62baf4636f3e
Create Date: 2025-03-25 11:50:50.517325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85139750dc79'
down_revision: Union[str, None] = '62baf4636f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('thread_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_histories', 'thread_id')
    # ### end Alembic commands ###
